// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	domain "PlataTest/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Quote is an autogenerated mock type for the Quote type
type Quote struct {
	mock.Mock
}

// CreateQuote provides a mock function with given fields: ctx, pair
func (_m *Quote) CreateQuote(ctx context.Context, pair string) (int, error) {
	ret := _m.Called(ctx, pair)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuote")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, pair)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, pair)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pair)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestQuote provides a mock function with given fields: ctx, pair
func (_m *Quote) GetLatestQuote(ctx context.Context, pair string) (*domain.Quote, error) {
	ret := _m.Called(ctx, pair)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestQuote")
	}

	var r0 *domain.Quote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Quote, error)); ok {
		return rf(ctx, pair)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Quote); ok {
		r0 = rf(ctx, pair)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Quote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pair)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuoteById provides a mock function with given fields: ctx, id
func (_m *Quote) GetQuoteById(ctx context.Context, id int) (*domain.Quote, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuoteById")
	}

	var r0 *domain.Quote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Quote, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Quote); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Quote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateQuote provides a mock function with given fields: ctx, id, price
func (_m *Quote) UpdateQuote(ctx context.Context, id int, price float64) error {
	ret := _m.Called(ctx, id, price)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, float64) error); ok {
		r0 = rf(ctx, id, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *Quote) UpdateStatus(ctx context.Context, id int, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuote creates a new instance of Quote. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuote(t interface {
	mock.TestingT
	Cleanup(func())
}) *Quote {
	mock := &Quote{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
